# Suggestions from kernel-hardening-checker

# Enable hardening of BPF just-in-time compiler for all users.
net.core.bpf_jit_harden = 2

# Disable unprivileged calls to bpf()
kernel.unprivileged_bpf_disabled = 1

# Number of kernel oopses after which the kernel should panic when panic_on_oops is not set
kernel.oops_limit = 100
# Number of kernel warnings after which the kernel should panic when panic_on_warn is not set.
kernel.warn_limit = 100

# Disallow ftrace function tracepoint, raw tracepoint access, CPU events access, and kernel
# profiling by users without CAP_PERFMON
kernel.perf_event_paranoid = 3

# kernel pointers exposed via /proc and other interfaces printed using %pK will be replaced
# with 0s regardless of privileges.
kernel.kptr_restrict = 2

# no processes may use ptrace with PTRACE_ATTACH nor via PTRACE_TRACEME. This may affect for
# example debuggers.
kernel.yama.ptrace_scope = 3

# symlinks are permitted to be followed only when outside a sticky world-writable directory,
# or when the uid of the symlink and follower match, or when the directory owner matches the
# symlink's owner.
fs.protected_symlinks = 1
# hardlinks cannot be created by users if they do not already own the source file, or do not
# have read/write access to it.
fs.protected_hardlinks = 1
# don't allow O_CREAT open on FIFOs that we don't own in world or group writable sticky
# directories, unless they are owned by the owner of the directory.
fs.protected_fifos = 2
# don't allow O_CREAT open on regular files that we don't own in world or group writable
# sticky directories, unless they are owned by the owner of the directory.
fs.protected_regular = 2

# Prevent users from being able to create namespaces.
# NOTE: This doesn't seem to have effect in Systemd
user.max_user_namespaces = 0

# Do not accept router advertisements
net.ipv6.conf.all.accept_ra = 0
net.ipv6.conf.default.accept_ra = 0

# Suggestions from lynis:

# Enable strict mode for reverse path
net.ipv4.conf.all.rp_filter = 1

# Disable sending redirects
net.ipv4.conf.all.send_redirects = 0

# Do not accept redirects or packets with SRR option by default
net.ipv4.conf.default.accept_redirects = 0
net.ipv4.conf.default.accept_source_route = 0

# Log packets with impossible addresses
net.ipv4.conf.default.log_martians = 1

# Do not accept redirects in IPv6
net.ipv6.conf.all.accept_redirects = 0
net.ipv6.conf.default.accept_redirects = 0
